---
- hosts: nexus
  vars:
      nexus_install: true
      nexus_create_repos: true
      nexus_install_self: false
      nexus_server: nexus.t.st
      nexus_version: 3.34.1-01
      pkg_location: https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.34.1-01-unix.tar.gz
      oc_pkg_location: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.8.12
      grpcurl_url: https://github.com/fullstorydev/grpcurl/releases/download/v1.8.5/grpcurl_1.8.5_linux_x86_64.tar.gz
      admin_pass: 'redhat'
  roles:
    - role: cicd
