---
- hosts: all
  vars:
      nexus_install: true
      nexus_create_repos: true
      nexus_install_self: false
      nexus_server: nexus.t.st
      nexus_version: 3.34.1-01
      pkg_location: https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.34.1-01-unix.tar.gz
      oc_pkg_location: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.8.12
      grpcurl_url: https://github.com/fullstorydev/grpcurl/releases/download/v1.8.5/grpcurl_1.8.5_linux_x86_64.tar.gz
      admin_pass: 'redhat'
      user_git: ansible
      ova_url: https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.8/48.84.202106301921-0/x86_64/rhcos-48.84.202106301921-0-vmware.x86_64.ova
      proxy_env:
        http_proxy: ""
        https_proxy: ""
  roles:
    - role: cicd
