---
- hosts: all
  vars:
      nexus_install: true
      nexus_server: nexusfull.labtest.com.py
      pkg_location: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
      nexus_version: 3.34.1-01
      admin_pass: '123456789'
  roles:
    - role: cicd
...
