---
# handlers file for cicd

# Reload Systemd Configs
- name: reload systemd
  systemd:
    daemon_reload: yes

# Start firewalld
- name: start firewall
  systemd:
    name: firewalld
    state: started
    enabled: yes

# Restart firewalld
- name: restart firewall
  systemd:
    name: firewalld
    state: restarted

# Disable selinux
- name: set selinux
  selinux:
    policy: targeted
    state: permissive

# Start service
- name: start service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes

# Restart service
- name: restart service
  systemd:
    name: "{{ service_name }}"
    state: restarted

# Start Nginx service
- name: start nginx
  systemd:
    name: nginx
    state: started
    enable: yes

# Restart Nginx service
- name: restart nginx
  systemd:
     name: nginx
     state: restarted
# Create admin pass
- name: crear admin
  wait_for:
    path: "{{ install_location }}/sonatype-work/nexus3/admin.password"

# Read admin
- name: read admin
  command: "cat {{ install_location }}/sonatype-work/nexus3/admin.password"
  register: adminpass
# Show admin
- name: show admin
  debug:
    var: adminpass.stdout
