---
# handlers file for cicd

# Start Nginx service
- name: start nginx
  systemd:
    name: nginx
    state: started
    enable: yes

# Restart Nginx service
- name: restart nginx
  systemd:
     name: nginx
     state: restarted
