---
# tasks file for cicd

#   Firewall
- name: Firewall | Add specific variables
  include_vars: "firewall.yml"

- name: Firewall | Add Firewall tasks
  include_tasks: "firewall.yml"

#   Nexus
- name: Nexus | Add specific variables
  include_vars: "nexus.yml"

- name: Nexus | Add Nexus tasks
  include_tasks: "nexus.yml"
  when: nexus_install and nexus_install_self == false

# Nginx 
- name: Nginx | Add Nginx self certificate tasks
  include_tasks: "nginx_self.yml"
  when: nexus_install and nexus_install_self

- name: Nginx | Add Nginx tasks
  include_tasks: "nginx.yml"
  when: nexus_install

# Repositories

- name: Nexus | Add specific variables
  include_vars: "ocp.yml"

- name: Nexus | Add Nexus Repos
  include_tasks: "repos_ocp4.yml"
  when: nexus_create_repos
