---
- name: Nginx | Create dirtectory
  file:
    path: "{{ item }}"
    state: directory
  loop:
      - /etc/pki/nginx/
      - /etc/pki/nginx/private/

- name: Nginx | Copy Certificate
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: server.crt, dest: /etc/pki/nginx/server.crt }
    - { src: server.key, dest: /etc/pki/nginx/private/server.key }

- name: Nginx | Copy ssl.conf
  copy:
    src: ssl.conf
    dest: /etc/nginx/conf.d/ssl.conf
  notify:
     - restart nginx
